// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsTemperatureReadings } from "./BmsTemperatureReadings";
import type { BmsVoltageReadings } from "./BmsVoltageReadings";
import type { Device } from "./Device";
import type { FaultSeverity } from "./FaultSeverity";
import type { MeasurementValue } from "./MeasurementValue";
import type { Percent } from "./Percent";

export type BmsMessage = { "frame": "voltages", source: Device, readings: BmsVoltageReadings, } | { "frame": "temperatures", source: Device, readings: BmsTemperatureReadings, } | { "frame": "balancing", source: Device, active_cell: number, duty_cycle: Percent, } | { "frame": "faults", source: Device, code: number, severity: FaultSeverity, } | { "frame": "setValue", source: Device, target: MeasurementValue, } | { "frame": "reset", source: Device, } | { "frame": "ping", source: Device, };
