// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Volts } from "./Volts";

export type BmsVoltageReadings = { pack: Volts, minCell: Volts, maxCell: Volts, averageCell: Volts, };
