// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { ImuSample } from "./ImuSample";
import type { MeasurementValue } from "./MeasurementValue";
import type { Rpm } from "./Rpm";
import type { TemperatureSample } from "./TemperatureSample";

export type DaqMessage = { "frame": "temperature", source: Device, samples: [TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample], } | { "frame": "wheelSpeed", source: Device, rpm: Rpm, } | { "frame": "imu", source: Device, samples: [ImuSample, ImuSample, ImuSample, ImuSample, ImuSample], } | { "frame": "tbd", source: Device, value: MeasurementValue, };
