// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Acceleration } from "./Acceleration";
import type { AngularAcceleration } from "./AngularAcceleration";

export type ImuSample = { acceleration: Acceleration, angularAcceleration: AngularAcceleration, };
