// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsMessage } from "./BmsMessage";
import type { DaqMessage } from "./DaqMessage";
import type { VcuMessage } from "./VcuMessage";

export type Message = { "system": "daq", "message": DaqMessage } | { "system": "bms", "message": BmsMessage } | { "system": "vcu", "message": VcuMessage };
