// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Celsius } from "./Celsius";

export type TemperatureSample = { tire: Celsius, brake: Celsius, };
