// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { MeasurementValue } from "./MeasurementValue";
import type { NewtonMeters } from "./NewtonMeters";

export type VcuMessage = { "frame": "torqueRequest", source: Device, torque: NewtonMeters, } | { "frame": "setValue", source: Device, target: MeasurementValue, } | { "frame": "reset", source: Device, } | { "frame": "ping", source: Device, };
